### ISSUE TITLE
findBlocks() not finding blocks within distance but in a different chunk

### ISSUE THREAD

**Issue by elamperti** [PrismarineJS/mineflayer#1189]
[x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.24.0
 - server: vanilla/spigot/paper vanilla 1.16.1
 - node: 14.2

## Detailed description of a problem
`bot.findBlocks()` isn't retreiving blocks within the given distance when those blocks are in a different chunk.

![2020-07-26_15 42 48 png](https://user-images.githubusercontent.com/910672/88486935-b12f6880-cf57-11ea-9b29-2a8bb7b44a12.jpg)

## Current code
```js
bot.findBlocks({
  matching: mcData.blocksByName.magma_block.id,
  point: targetBlock.position,
  maxDistance: 2,
});
```

## Expected behavior
It should return an array containing coords for both magma blocks. Instead, it just returns the coords for the magma block within the current chunk.

## Additional context
It _does_ work correctly when magma blocks are within the chunk.

**Comment by wvffle** [comment]
Did you try increasing `maxDistance`?

**Comment by Karang** [comment]
2 things come to mind when I'm looking at your code and screenshot:
* the magma block you look at seems to be more than 2 blocks away (your maxDistance parameter)
* you don't set the minCount option which by default is 1 (this mean that the algorithm will return you a minimum of 1 block, if you want to be guaranteed to have more than 1 block, you need to increase this property)

https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botfindblocksoptions

**Comment by elamperti** [comment]
@Karang I tried with a maxDistance of 5 before opening this issue; the same code testing for blocks in the same distribution but within the chunk returns the two blocks correctly. It's a problem at the chunk boundary

**Comment by Karang** [comment]
how many blocks does the function return ? what did you set minCount to ?

**Comment by elamperti** [comment]
At other point where all blocks were within the chunk, it did return two as expected. I didn't set minCount in either case.

**Comment by Karang** [comment]
that is perfectly normal: the default for minCount is 1 so you ask the algorithm 'return me at least 1 block'. So the algorithm is free to return you any number of block it wants as long at it returns you at least 1 block. If you want 2 block, you have to set minCount to 2 so you are guaranteed to get at least 2 blocks (if there is 2 blocks within maxDistance). Due to some internal optimisations the algorithms search chunk by chunk, if after looking in the current chunk it found enough block to satisfy your request it will not look in the next chunk, if it found more it will return everything it has found.
