### ISSUE TITLE
Find position of bot and block bot 's looking at

### ISSUE THREAD

**Issue by hammarez** [PrismarineJS/mineflayer#1216]
- [х] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [х] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [х] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 1.12.2
 - server: vanilla/spigot/paper  spigot
 - node: 12.16.1

## Detailed description of a question

can I somehow find out which coordinates of the block the bot is looking at, if not, how do I find out what coordinates the bot itself is standing on?

**Comment by IdanHo** [comment]
You obviously didnt actually read the API documentation, because it has the answers to both of those questions.

**Comment by wvffle** [comment]
The tittle of the issue is not in corelation with the questions asked. Both examples and API contains answers to your questions, so as @IdanHo stated, you haven't even read those. 

Besides, I've already shown you how to get the block the bot's looking at in https://github.com/PrismarineJS/mineflayer/issues/1215#issuecomment-670501536. 

Next thing is to access the `position` attribute of the given block. Same goes with the bot entity. The entity can be accessed through `bot.entity` where `bot` is an instance of your bot

**Comment by wvffle** [comment]
Please close that issue if you feel like it's resolved or provide more info on the topic
