### ISSUE TITLE
how to dig the blocks that the bot is looking at?

### ISSUE THREAD

**Issue by flymer5** [PrismarineJS/mineflayer#1228]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: #.#.#
 - server: vanilla/spigot/paper 1.12.2
 - node: 12.18.3

## Detailed description of a question
how to dig the blocks that the bot is looking at?

**Comment by wvffle** [comment]
>- [x]  I have carefully read the API documentation and it does not contain an answer to my question.

**It does contain an answer. Read it before you tick it... Those checkboxes are there for some reason, if you haven't read the API or examples (which contain an answer as well) then just don't tick them....**

Here are links from the API **that you obviously have read as you ticked it**. They contain an answer to your question, simply get the block in sight and then use that block to dig it.
- https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botblockinsightmaxsteps-vectorlength
- https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botdigblock-forcelook--true-callback

If you have now any more questions regarding this topic, please comment back. Otherwise, if you feel like your issue is solved, please close this ticket.

**Comment by flymer5** [comment]
I read, only when using the first method I got an error related to physics. So I wanted to ask, maybe I'm thinking wrong

**Comment by Karang** [comment]
Then post the error instead.

**Comment by flymer5** [comment]
![image](https://user-images.githubusercontent.com/58649986/89792466-67917100-db46-11ea-96a1-5031e043477e.png)
Error

**Comment by Karang** [comment]
This is most likely because the lookAt position argument you give in your bot.js file at line 98 is not an instance of vec3. But show your code, we are not supposed to guess it.

**Comment by flymer5** [comment]
thanks, I already fixed it. But now another error has appeared
![image](https://user-images.githubusercontent.com/58649986/89794684-35354300-db49-11ea-9b82-311eeebec4a2.png)
Code:
`let i = 5;
		const lookv = new Vec3(-367, 7, -24);
		bot.lookAt(lookv)
		while(i<10) {
			const position = new Vec3(bot.blockInSight(5, 5/16));
			const block = bot.blockAt(position);
			bot.dig(block);
		};`

**Comment by Karang** [comment]
BlockInSight returns a block

**Comment by flymer5** [comment]
How to get coordinates?

**Comment by Karang** [comment]
block.position

**Comment by flymer5** [comment]
thank!

**Comment by flymer5** [comment]
![image](https://user-images.githubusercontent.com/58649986/89799540-716ba200-db4f-11ea-9b11-3bdda7886fbe.png)

**Comment by Karang** [comment]
It can also return undefined if there is no Block in sight within max distance. I suggest you take a step back and learn a bit of js and how to do simple debugging, otherwise it can go on forever.

**Comment by flymer5** [comment]
But the block stands in front of him

**Comment by flymer5** [comment]
When withdrawing bot.blockInSight(5, 5/16) displays all data about the block, including coordinates. But if you output only coordinates, then it outputs undefined
