### ISSUE TITLE
Bot get kicked when standing at the center of a hopper block

### ISSUE THREAD

**Issue by Denaryplanet** [PrismarineJS/mineflayer#1295]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.28.1
 - server: spigot 1.12.2
 - node: 12.18.3

## Clear question
How to make the bot can stand on the edge of the funnel after the restart, otherwise after the restart it rises to the center and kicks it. Maybe there are physics settings or something like that?
## What did you try yet?
-
## Your current code
-
## Additional context
-

**Comment by Karang** [comment]
Fill the template and be explicit about your issues...

**Comment by flymer5** [comment]
> Fill the template and be explicit about your issues...

So I have nothing to fill ...

**Comment by Karang** [comment]
Then you have no issue ?

Give some context, we don't know what "the funnel" is or what your bot is doing. It is not the first time you open an issue like this. We want to help, but you'll have to learn how to communicate your issues, otherwise they will remain unanswered.

**Comment by flymer5** [comment]
> Then you have no issue ?
> 
> Give some context, we don't know what "the funnel" is or what your bot is doing. It is not the first time you open an issue like this. We want to help, but you'll have to learn how to communicate your issues, otherwise they will remain unanswered.

sorry, I just don't know much English. Now I will try it more clearly

**Comment by flymer5** [comment]
There is a generator in which the bot is digging. so that resources do not go to waste, you need to put a hopper under the player. If the bot is placed on the hopper from the edge, it will not be kicked. But if you stand in the center of the hopper, the bot will kick almost instantly. How to make sure that after a restart to the server the bot does not get up to the center of the block(hopper)?

**Comment by Karang** [comment]
Ok, it is much clearer now. You see how adding a bit of context help us understand ?

Now, it would be interesting to understand why standing in the center of a hopper kick the bot. What is the kick reason ?

**Comment by flymer5** [comment]
> There is a generator in which the bot is digging. so that resources do not go to waste, you need to put a hopper under the player. If the bot is placed on the hopper from the edge, it will not be kicked. But if you stand in the center of the hopper, the bot will kick almost instantly. How to make sure that after a restart to the server the bot does not get up to the center of the block(hopper)?



> Ok, it is much clearer now. You see how adding a bit of context help us understand ?
> 
> Now, it would be interesting to understand why standing in the center of a hopper kick the bot. What is the kick reason ?

Kicks for no reason and it seems only on version 1.12.2

**Comment by Karang** [comment]
There is no such things as "kicks for no reason". What's the kick message ?

**Comment by Denaryplanet** [comment]
> There is no such things as "kicks for no reason". What's the kick message ?

Just throws it out of the server, with an error ECONNRESET

**Comment by Karang** [comment]
nothing on:
```js
// Log errors and kick reasons:
bot.on('kicked', (reason, loggedIn) => console.log(reason, loggedIn))
bot.on('error', err => console.log(err))
```
?

**Comment by Denaryplanet** [comment]
> nothing on:
> 
> ```js
> // Log errors and kick reasons:
> bot.on('kicked', (reason, loggedIn) => console.log(reason, loggedIn))
> bot.on('error', err => console.log(err))
> ```
> 
> ?

Yes

**Comment by Karang** [comment]
I tried it on a 1.12.2 vanilla server, there are no issues with hoppers. When the bot is standing in the middle of the hopper block it goes slightly inside the hole (like any vanilla client). When it logs out and in again it is at the same position, where it should.

If there is something about your server that doesn't allow that, it is non-vanilla behavior and we cannot support every special server use case. Unless you provide a way to consistently reproduce the issue, there is no way we can help.

Reopen this issue if you have more information, otherwise you'll have to do some debugging on your own.
