### ISSUE TITLE
Implement instant breaking

### ISSUE THREAD

**Issue by kirillbul** [PrismarineJS/mineflayer#1673]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: lastest
 - server: spigot 1.16.4
 - node: 15

## Clear question
How can I get block hardness? And the hardness of the pickaxe (which the player is holding in his hand)?

## What did you try yet?

None

## Your current code

None

## Additional context

None

**Comment by u9g** [comment]
basic code: 
```js
const mcData = require('minecraft-data')('1.16.5')
const stone = mcData.blocksByName.stone
console.log(`Stone hardness: ${stone.hardness}`)
//dig time
const Block = require("prismarine-block")("1.16.5")
const diamondPickaxe = mcData.itemsByName.diamond_pickaxe.id
const stoneBlock = new Block(stone.id,1,0)
const digTime = stoneBlock.digTime(diamondPickaxe)
console.log(`Breaking this block will take ${digTime}ms.`)
```
running the code: https://runkit.com/u9g/block-hardness
to get the item in the bot's hand, you can do: `bot.inventory.slots[HAND_SLOT]`

**Comment by goncharovchik** [comment]
> basic code: 
> ```js
> const mcData = require('minecraft-data')('1.16.5')
> const stone = mcData.blocksByName.stone
> console.log(`Stone hardness: ${stone.hardness}`)
> //dig time
> const Block = require("prismarine-block")("1.16.5")
> const diamondPickaxe = mcData.itemsByName.diamond_pickaxe.id
> const stoneBlock = new Block(stone.id,1,0)
> const digTime = stoneBlock.digTime(diamondPickaxe)
> console.log(`Breaking this block will take ${digTime}ms.`)
> ```
> running the code: https://runkit.com/u9g/block-hardness
> to get the item in the bot's hand, you can do: `bot.inventory.slots[HAND_SLOT]`

hmm, I need exactly the values hardness, not DigTime

**Comment by imharvol** [comment]
Do you mean Pickaxe Durability?

**Comment by goncharovchik** [comment]
> Do you mean Pickaxe Durability/Uses?

No, I want to do an `Instant mining`

#From Minecraft Wiki

`When breaking a block, a tool and its enchantments do its speed value as "damage" to a block every game tick, and when that value equals or exceeds the block's hardness, the block breaks. If the tool and enchantments immediately equal or exceeds the hardness times 30, the block breaks with no delay; otherwise a 6 tick (3⁄10) second delay occurs before the next block begins to break.`

**Comment by u9g** [comment]
Discussed in discord. Info to complete: > Karang: seems like instant breaking not implemented https://minecraft.gamepedia.com/Breaking#Calculation
its just a if () to add though. should go there https://github.com/PrismarineJS/prismarine-block/blob/master/index.js#L182 seems like the wiki was updated quite a lot since the digTime function was implemented https://minecraft.gamepedia.com/Breaking?action=history

**Comment by u9g** [comment]
implemented here: https://github.com/PrismarineJS/prismarine-block/pull/27
