### ISSUE TITLE
What's needed for 1.17/snapshot support?

### ISSUE THREAD

**Issue by KaidenP** [PrismarineJS/mineflayer#1730]
What's needed for 1.17/snapshot support? I can't imagine it's already working, but I'll likely try it soon.

**Comment by Karang** [comment]
A lot is needed, especially since they changed a lot of things. Stuff that should be updated in order:
* minecraft-data https://github.com/PrismarineJS/minecraft-data/blob/master/doc/add-data-new-version.md
* prismarine-chunk
* prismarine-world
* mineflayer
We don't plan to support snapshot, so we'll wait for the 1.17 release, but feel free to start working on it.

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-contribute#updating-to-new-minecraft-versions that's the process to update prismarinejs stuff in general for a new version

if you want 1.17 to be supported earlier, you could start by updating protocol.json for the latest snapshot using https://wiki.vg/Pre-release_protocol as a reference

We sometimes support snapshots in minecraft-protocol, but usually not in mineflayer

**Comment by KaidenP** [comment]
You're absolutely right, should've looked over there first.
