### ISSUE TITLE
fix bot.dig

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/mineflayer#1780]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: newest
 - server: vanilla/spigot/paper vanilla
 - node: 14

## Detailed description of a problem
The dig function breaks when you break many blocks in a row because it doesnt properly await it's promise

## What did you try yet?
?

Did you try any method from the API? `bot.dig`
Did you try any example? Any error from those? the farmer example is broken because of this

## Your current code

the farming example

## Expected behavior
the bot.dig promise to be properly awaited

## Additional context
nothing

**Comment by rom1504** [comment]
Can you explain how you checked that?

**Comment by rom1504** [comment]
I think what needs doing here is adding a test that checks mineflayer properly emits a warning if you try to call dig multiple times without waiting

**Comment by Karang** [comment]
I think this could be closed. Did some testing, `dig` do wait for the block to be updated, but the first blockUpdate event triggered is the one from the client side prediction, so it resolve immediately.

IMO its the correct behavior, since you don't necessarily want to wait for the server to answer before doing other actions.

Bugs can be avoided by properly checking that we are allowed to dig before doing it.
