### ISSUE TITLE
Add a bot.placeEntity() function

### ISSUE THREAD

**Issue by Karang** [PrismarineJS/mineflayer#1824]
It should be similar to placeBlock but expect an entity to be placed and resolve the promise when the entity is spawning.

It could be used for end_crystals, boats, armor_stands, spawn eggs, etc...

At the moment, people are using placeBlock for that but the promise is always rejected because the entity spawns but the block is never updated.

**Comment by u9g** [comment]
so it could be the same as placeblock just await entity spawn instead of block update

**Comment by Karang** [comment]
> so it could be the same as placeblock just await entity spawn instead of block update

Yes, it could also return the entity so we could write something like:
```js
const crystal = await bot.placeEntity(block, faceVector)
await bot.attack(crystal)
```

**Comment by LenniDev** [comment]
I know that this is already possible with:

`bot.equip(crystal_item)
await bot.placeBlock(obsidianBlock,new Vec3(0,1,0))
await bot.attack(crystal)`

The obsidian block is the block where the crystal should be placed on top of.  This is probably also possible with other entitys.
The problem is that this raises an error and disconnects the bot.

I have found this code here: [Solution Origin](https://github.com/LINKdiscordd/mineflayer-autocrystal/blob/main/src/AutoCrystal.ts)

I know that this isnt the best solution but maybe you need a quick fix.

**Comment by u9g** [comment]
I'm working on this, with my pr open, just that progress has stalled a bit due to the boat test

**Comment by u9g** [comment]
done in https://github.com/PrismarineJS/mineflayer/pull/1830
