### ISSUE TITLE
mod support?

### ISSUE THREAD

**Issue by lowerforce77** [PrismarineJS/mineflayer#2321]
Would it be possible to use a mod loader such as fabric or forge to join a modded server that Isn’t vannila.

**Comment by u9g** [comment]
It’s not reasonable to expect mod support since fabric mods use java specific methods that aren’t available in mineflayer. Mods rely on being able to take from the actual game code of minecraft, such as the java methods they use internally, which isn’t really possible here considering we don’t use mojang’s java code at all.

**Comment by 1ProCrafters** [comment]
Forge: https://github.com/PrismarineJS/node-minecraft-protocol-forge
Fabric: Not yet
#56
#472

**Comment by nickelpro** [comment]
Note that the forge package is only to make connecting to forge servers possible, it does not and cannot "support mods". There's no way for Mineflayer to become aware of different packets/blocks/plugin channels that a given Forge mod might implement.

AFAIK there's no special handshake for a Fabric server, so Mineflayer supports Fabric as much as it supports Forge (which is not much).

**Comment by vico93** [comment]
Sorry to necro this thread, first i would like to know if a Fabric's counterpart of `node-minecraft-protocol-forge` is still planned to be made but also to ask if would be theoretically possible to modders to write plugins on mineflyer side to actually add the basic funcionality on mineflayer's side.
