### ISSUE TITLE
Random teleportation

### ISSUE THREAD

**Issue by demipixel** [PrismarineJS/mineflayer#258]
Experience with my bot (some with rbot as well) has shown that on connection (most reliable) and at other random times, the bot will teleport downwards a certain amount (Around 15-20 blocks although I don't think this is very reliable) into a cave, lava, the void, etc. Any clue why this might be happening and how we can fix it?

**Comment by rom1504** [comment]
I have noticed this too. I'm pretty sure it was due to lag since I only noticed this when connecting the bot to a distant server and not to localhost.

Basically I think the bot keep sending position update (moving forward for example) but the server get them only a few seconds later so in the vanilla client you only get them a few seconds later too, so it appears it's teleporting.

I think we should somehow check the latence and adapt physics.js accordingly.

**Comment by rom1504** [comment]
Can we figure out a reproducible test case for this ? (I don't want to test this by waiting the bot to do this by himself 30min later)
