### ISSUE TITLE
C/C++ binding support

### ISSUE THREAD

**Issue by Dashbloxx** [PrismarineJS/mineflayer#3147]
## Is your feature request related to a problem? Please describe.
There's no library for C programs allowing people to create Minecraft bots.

## Describe the solution you'd like
I think it would be good for mineflayer to add support for calling it's functions from C and/or C++.
## Describe alternatives you've considered
I've considered writing my own library, but have realized that  there's no point in doing so when an already existing library could add support for C/C++.

## Additional context
It would be great for people trying to write fast and lightweight Minecraft bots.

**Comment by extremeheat** [comment]
Can you explain why you would want to write a Minecraft bot in C++?  mineflayer only works because the rich package ecosystem and asynchronous capabilities in Node.js. Languages like C++ are pretty bad for most application programming. You can easily write 2x the code, have half the features and spend far more brain time coding and debugging that could be spent on useful application functionality. So I don't understand the use-case here. I am more understanding of Python, as it has a large package ecosystem like Node.js and is widely used for scientific/research applications.

> I think it would be good for mineflayer to add support for calling it's functions from C and/or C++.

If you need to call bot functions in an existing program not written in Node.js, your two ways to do this are either via stdin/stdout pipes or by running a web server or some other socket server and then doing remote procedure calls.

> It would be great for people trying to write fast and lightweight Minecraft bots.

Why do you believe mineflayer is not fast or lightweight? Did you find a bottleneck somewhere?

**Comment by Dashbloxx** [comment]
I find it easier to write in C. Most of the projects I make are written in C. I guess I'll just write my own.

**Comment by rom1504** [comment]
You can try to build something like https://github.com/extremeheat/JSPyBridge

But yeah it's a little surprising

**Comment by PondWader** [comment]
It would probably be better to use Node.js native support for C++ addons than bridging over stdout/stderr: https://nodejs.org/api/addons.html

But you're not really getting the performance gains of C++ as Mineflayer is still running in JS and for most bots it's mineflayer that is doing the heavy lifting.

**Comment by extremeheat** [comment]
A Node.js add on would only work if the base program is written in Node. Otherwise he would need to compile V8 with Node.js runtime and all the other dependencies and embed it into his build step. And it takes quite a long time to build them clean, FWIW.

**Comment by PondWader** [comment]
Yes but if I understand them correctly they just want to be able to use C++ to make a bot, which it would work for, just having a simple node.js entrypoint to load the addon. But even that seems like more work than it's worth having to deal with v8 types when you could just write JavaScript which really shouldn't be that hard to pickup if you already know C & C++ quite well.

**Comment by Dashbloxx** [comment]
Yeah I'm thinking of writing my own library. I might update this soon if I'm able to make a functioning one.

**Comment by rom1504** [comment]
Do you mean a bridging library or rewriting a mc client from scratch?
If your goal is to write a bot rather than learning network coding, I'd recommend using mineflayer instead.
