### ISSUE TITLE
Failed to verify username

### ISSUE THREAD

**Issue by jeanzob** [PrismarineJS/mineflayer#3185]
Using Python.

## Detailed description of a problem
Cannot login to a specific Paper server. Works on local, works on other servers.

Server version: 1.20.1

## Server side error:

```
[ERR] [11:03:15] Username 'USERNAME' tried to join with an invalid session
[INFO] [11:03:15] <IP> lost connection: Failed to verify username!
```

## What I tried

1. Logging directly with username/password (same behaviour)
2. Logging without password / by token (same behaviour)
3. Log off my account on MC launcher and try again (same behaviour)

## Your current code
```python

from javascript import require, On

mineflayer = require('mineflayer')

bot = mineflayer.createBot({
  'host': 'server-domain',
  'port': 25565,
  'username': 'USERNAME",
  'auth': 'microsoft',
  'hideErrors': False
})

bot.loadPlugin(commands.pathfinder.pathfinder)

@On(bot, 'spawn')
def handle(*args):

  @On(bot, 'chat')
  def handleMsg(this, sender, message, *args):
    print('msg')
```

**Comment by extremeheat** [comment]
If you want to force a token refresh, you would need to change the `username` you supply to createBot. We should probably have an option in pauth to force a refresh. This seems to be a common issue, so there may be a problem inside prismarine-auth handling.

If you don't mind sharing the server IP, that could help in investigating. Otherwise try checking if you can reproduce on a local Paper server.

**Comment by boredcoder411** [comment]
Same error here, but with a fabric server, and using offline auth

**Comment by boredcoder411** [comment]
I don't feel comfortable sharing the IP for my server, as it is on my home network. However, I could send a zip file with the server directory so you can test personally, if that helps

**Comment by boredcoder411** [comment]
I solved it by going into the server.properties file, and changing online-mode from true to false
