### ISSUE TITLE
1.20.4 support

### ISSUE THREAD

**Issue by PurritoTheCoder** [PrismarineJS/mineflayer#3247]
I need 1.20.4

**Comment by rom1504** [comment]
you can start by helping at https://github.com/PrismarineJS/mineflayer/pull/3243

**Comment by 3jq** [comment]
please add 1.20.4

**Comment by Jammeren2** [comment]
https://github.com/Jammeren2/Mineflayer-1.20.4
Support for version 1.20.4 works here. 1.20.3 not supported

**Comment by extremeheat** [comment]
Instead of doing that you should help contribute to the PRs

**Comment by KTibow** [comment]
@Jammeren2 what did you change to get this to function?

**Comment by EvModder** [comment]
> https://github.com/Jammeren2/Mineflayer-1.20.4 Support for version 1.20.4 works here. 1.20.3 not supported

I see no diffbase against the original forked repo, so it's highly possible this can contain hidden malicious code.
Just as a warning to future readers of this thread looking for 1.20.4

It's an unfortunate reality the Mineflayer project is always incredible slow to update to newer versions compared to other tools due to lack of interest from project owners and lack of knowledge from users seeking to update it themselves, but that shouldn't be enough of a reason to download node modules that don't link back to the forked source.

**Comment by rom1504** [comment]
Please share any other network implementation of the protocol which is updating faster than mineflayer. I don't know of any

**Comment by rom1504** [comment]
If you care about the update please help at https://github.com/PrismarineJS/node-minecraft-protocol/pull/1275

For now 2 people spent a bit of time. Minor fixes are left

**Comment by boredcoder411** [comment]
Now that https://github.com/PrismarineJS/node-minecraft-protocol/pull/1275 has been merged, and there is a release, when is support coming here?

**Comment by rom1504** [comment]
It's done
