### ISSUE TITLE
Improve supported version check

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#3257]
checking the major is not enough anymore as mojang is doing breaking changes in minor version now

we should have a range based system

**Comment by rom1504** [comment]
this line https://github.com/PrismarineJS/mineflayer/blob/48c3ca71ea5822c4304ec74951970dbefd5026eb/lib/loader.js#L112

**Comment by extremeheat** [comment]
Probably just looking at if protocol version >= supported protocol version would work. Since not all patch updates have protocol version bump.

**Comment by rom1504** [comment]
Mineflayer is not only about protocol though so better check against the exact version rather than protocol only

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/48c3ca71ea5822c4304ec74951970dbefd5026eb/lib/loader.js#L118 this is doing the protocol check though, I don't know why it doesn't work

**Comment by extremeheat** [comment]
Might not have been tested when they were written, both the conditions resolve to `undefined`. Otherwise there may have been a change in prismarine-registry or node-minecraft-data handling that broke it. Not sure if the API properly define what should be returned from the loader function if the minecraft version is unknown. So that would have to be handled by adding extra conservative checks in mineflayer.

**Comment by rom1504** [comment]
thanks for fixing
