### ISSUE TITLE
Storing a fish in a chest

### ISSUE THREAD

**Issue by Slushpies** [PrismarineJS/mineflayer#435]
```js
function storeFish() {
	var blockChest = bot.findBlock({
    matching: [54],
	point: bot.players[master].entity.position,
  });
  console.log(blockChest);
  if(!blockChest) {
    console.log("no chest found");
    return;
  }
  var tempVar = vec3(blockChest.position.x, blockChest.position.y, blockChest.position.z);
  bot.navigate.to(tempVar); 
  var fish = bot.inventory.findInventoryItem(349);
  var chest = bot.openChest(blockChest);
  chest.on('open', function() {
    if (fish) {
            chest.deposit(fish.type, null, bot.inventory.count(fishI.type));
    }
  });
}
```

can anyone tell me why this is not storing the fish into the chest?

**Comment by rom1504** [comment]
You don't wait the bot.navigate to actually move to the correct position.
When you test it, at which step does it stop working ?

**Comment by Slushpies** [comment]
It moves to the chest but doesnt do anything after that. Doesnt the code get executed one line at a time?

**Comment by rom1504** [comment]
Yes it is, but the network implementation is non-blocking, which means you need to use callbacks or event to know when something is done.
For example you need to use the "arrived" event (see https://github.com/andrewrk/mineflayer-navigate README) to know when mineflayer navigate is arrived at the correct location. Otherwise you'll try to open the chest before arriving.

**Comment by Slushpies** [comment]
so,
bot.on("arrived" function() {
   etc.
}?

**Comment by rom1504** [comment]
yes

**Comment by Ezzer29** [comment]
I get this error when trying to open the chest:
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'offset' of null`
