### ISSUE TITLE
mods with chat commands

### ISSUE THREAD

**Issue by TheTechPony** [PrismarineJS/mineflayer#555]
Can the bots chat commands work like regular commands? I mean this in a sense of you have a mod that adds commands the bot's chat can be read by said mods.

**Comment by plexigras** [comment]
its maybe better if you ask questions over at gitter and use issues for issues with mineflayer

[![Join the chat at https://gitter.im/PrismarineJS/mineflayer](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/PrismarineJS/mineflayer?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

also i have no idea what you are talking about

**Comment by TheTechPony** [comment]
for example if I had a mod (minebot) and it added the chat command '/minebot clear' I would like the bot to be able to use the command as well. Currently if I type the command in chat it works but if I do bot.chat it does not and pushes the command to the server instead of the mod.

**Comment by plexigras** [comment]
mineflayer is a client and like any other client it cant see what commands another client is sending to the server

**Comment by TheTechPony** [comment]
Clientside Forge mods this is what I mean. The mod Minebot is a good example, I would like to be able to interact with this mod via chat however I can't make mineflayer press T and then type in the command like a player can therefore it sends the command straight to the server.

**Comment by roblabla** [comment]
That's basically impossible. Mineflayer can only do what a regular user can. You can't make another user type a command for them. That's what you're asking mineflayer to do here.

**Comment by TheTechPony** [comment]
Are you sure we understand my question? If I download the forge mod Minebot and open my chat to type /minebot build then it will build whatever; what I'm asking for is minebot to load my mods from the mods folder and have the commands added to the chat that way if I do bot.chat('/minebot build') it will run the command as well.

**Comment by TheTechPony** [comment]
Now that I think about it though that'd mean forge support would have to be added and that sounds like a lot of work so I don't reasonably expect this to be done.

**Comment by roblabla** [comment]
Ah now I understand.

No this is not possible, at least not right now. The thing is, clientside mods are basically modifications done on the raw minecraft .class files. We're nothing like the original minecraft, and don't even run on Java !

Technically speaking, it might be possible to use Doppio to emulate the forge API at least, to provide some basic support. But it's extremely complicated, would be super-slow, and IIRC a lot of the client-side plugins rely on minecraft internals in one way or another, so it wouldn't even work very well.

Now one thing *is* possible however. We already have forge support at the protocol layer (node-minecraft-protocol), meaning it's possible to send whatever custom packets your mods use to communicate to the server. This obviously won't work for minebot (since it doesn't really communicate with the server), but it'd work to support plugins like buildcraft, computercraft, IC2, etc...

If you have something specific from minebot you need, it'd be nice if you could explain the feature in details. We might be able to give you pointers to reproduce the feature with mineflayer :)

**Comment by TheTechPony** [comment]
I was thinking along the lines of being able to use the minebuild features from the mod;

/minebuild pos1 => /minebuild pos2 => /minebuild clear (quarry for clearing out large areas)
/minebuild build schematic (building schematics in game)

**Comment by roblabla** [comment]
so building a schematic is actually something various people worked on, but I don't think anyone ever quite finished it. There are, however, libraries to load schematics, e.g. https://github.com/1b8/schematic. The building part is probably not too complicated, if you use mineflayer-scaffold for instance.

For the clearing part, there is https://github.com/Darthfett/helperbot/blob/73c28c773a7c6790db7020ff25173618f9f54af9/lib/plugins/stripmine.js that does strip mining. It does quite a lot of complicated logic to ensure it doesn't fall into lava or whatever if not in creative mode, which you might find interesting.

**Comment by TheTechPony** [comment]
I'm planning on making it identical to minebot's clear and I'm pretty sure I know how to sort out the logic required but I'm looking for some good examples of mining blocks without scaffold involved that way I can write an efficient quarry script; I also plan on publishing my bot when I'm finished that way others can learn as well. Thanks for the quick and awesome support, keep it up! :)
