### ISSUE TITLE
1.12.2 not supported and no error displayed

### ISSUE THREAD

**Issue by djalexd** [PrismarineJS/mineflayer#604]
Server: spigot git-Spigot-93e20b3-b8f84f3 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT), no plugins
Client: npm 5.4.2

Steps to reproduce:
1. clone repository
2. run any example. In my case I did ```node jumper.js 192.168.0.220 25565 ChanChan```
3. bot connects for a couple of seconds and then simply disconnects. I get this behavior constantly

On server side:
```
[22:41:21] [Server thread/INFO]: ChanChan lost connection: Disconnected
[22:41:21] [Server thread/INFO]: ChanChan left the game
```

I tried to debug the minecraft protocol, nothing seems off, client code is not throwing any errors. 

Same goes with vanilla server

**Comment by rom1504** [comment]
We don't support that version yet (it was released yesterday I think ?)
But an error should definitely be displayed. If it's not then that's a bug.

**Comment by rom1504** [comment]
#600 should help

**Comment by djalexd** [comment]
I could investigate with an earlier server version?

**Comment by rom1504** [comment]
yes

**Comment by djalexd** [comment]
I'll apply that patch tonight and check if it fixes the problem. Otherwise, will go to a previous version of spigot server

**Comment by djalexd** [comment]
Patch didn't help, bot's behavior is same: connects for a couple of seconds, but then disconnects.
However, reverting the server to `1.12` helped, bot doesn't disconnect anymore!

**Comment by rom1504** [comment]
What patch ?

**Comment by djalexd** [comment]
You suggest applying #600

**Comment by rom1504** [comment]
Ah yes, did you run npm update too ?

**Comment by djalexd** [comment]
`npm --version` --> `5.4.2`. The newest one suggested by npm is `5.5.1` but how can that PR be affected/resolved by newer version of npm? Code is pretty straightforward and just simplifies a couple if IFs

**Comment by plexigras** [comment]
`npm update` updates the npm packages not npm itself

**Comment by lluiscab** [comment]
Is this issue resolved somewhere? I've been trying for 2-3 days and I'm also getting the random disconnects from server ~20 seconds after join.

Client side just calls the `end` event.

Server side:

> [15:18:14 INFO]: test lost connection: Disconnected
> [15:18:14 INFO]: test left the game

**Comment by rom1504** [comment]
The resolution is not to try to use an unimplemented version or to
implement it.

(Also displaying an error but if you already know that's the problem, it's
kind of useless)

**Comment by lluiscab** [comment]
Well, any idea on how to implement a fix for this or how long I'll have to wait for mineflayer to implement one?

**Comment by BarnabyD** [comment]
1.12.2 seems to mostly work (it is listed as supported on minecraft-data)
The issue of disconnecting 20 seconds after joining seems to be because "Keep Alive" was changed in 1.12.2. (which is defaulted to 20 seconds)

It works with 25 or more seconds, so using mineflayer you can set the "checkTimeoutInterval" option.
`var mineflayer = require('mineflayer');`
`var bot = mineflayer.createBot({`
`  host: "localhost", // optional`
`  port: 25565,       // optional`
`  username: "email@example.com", // email and password are required only for`
`  password: "12345678",          // online-mode=true servers`
`  checkTimeoutInterval: (25 * 10000) // run KeepAlive every 25 seconds`
`});`

The original 20 seconds can be found in "minecraft-protocol\src\client\keepalive.js:7"
`const checkTimeoutInterval = options.checkTimeoutInterval || 20 * 1000;`

**Comment by thisismexp** [comment]
just thought:  Could it be that you are trying to access the game with two clients (bot and normal game) from the same machine. Most of the server implementations don't allow multiple clients with same ip address. And it got the same error when i was stupid enough to do this ;)

**Comment by rom1504** [comment]
1.13 supported
