### ISSUE TITLE
Convert message event to function

### ISSUE THREAD

**Issue by nagoL2015** [PrismarineJS/mineflayer#724]
Before you ask yes I have checked other issues. The chat event isn't working but the message on is. Although is there a way to use it as a function and get the username from it? Also not just the raw text?

**Comment by plexigras** [comment]
we should consider adding a "is `bot.on('chat', ...)` not working?" section to the issue template.

what is the output of `bot.on('message', m => console.log(m.toString()))`?

**Comment by roblabla** [comment]
What does "convert message event to function" even means?

The "chat" event attempts parsing the message to find the username from the raw text. It does this using a RegEx. By default, that regex works for the default chat stuff, but it doesn't work on server that use a plugin to customize the chat output. You'll need to customize the regex for it to work: https://github.com/PrismarineJS/mineflayer/blob/master/examples/chatAddPattern.js#L31

otherwise, you can parse the raw message from the "message" event directly.

**Comment by rom1504** [comment]
Done
