### ISSUE TITLE
Any way to use this with the mcleaks api?

### ISSUE THREAD

**Issue by unlimitedcoder2** [PrismarineJS/mineflayer#790]
https://mcleaks.net/apidoc show that there is a "session" in the response and I was wondering if it would be possible to use mineflayer with this code? I have looked into https://github.com/PrismarineJS/mineflayer/blob/master/examples/session.js but this seems to also need an access token and a client token as well as "id" which I believe is the session code. I have tried this but I get no output. https://owo.oooooooooooooo.ooo/i/6o3q.png

**Comment by rom1504** [comment]
Look at other issues about that

**Comment by unlimitedcoder2** [comment]
@rom1504 Could you give an example of an issue that relates to this as I could find none

**Comment by skullteria** [comment]
Hey dude, I'm happy that I found you in time :D. I'm basically trying to achieve the same thing and already did all the research. To research how to handle the auth part with mcleaks I just took the [AltLoader](https://mcleaks.net/altloader) which isn't supported by them anymore but was still there when I googled for it. Well all I needed to do to fix the AltLoader was decompile the mod, change http to https in the routes and recompile it back and pack it into the jar file. 
First thing I did was reimplement "the Redeem Token part" inside a html page with javascript to do the HTTPS POST. I used a proxy for the request because else CORS would have blocked it, but that's another story. Here the website, if you are interested in the js code [spamvictim.ml](http://spamvictim.ml/).

After that I was able to look through every part of the code(also some mc code). Alright let me try to summarize it up for you:
- Redeem Token through a HTTPS POST Request
- store the Session and the username u gathered(The session is only mcleaks related)
- Now when you go into the GuiConnecting Gui and try to connect to a server there will be a own packethandler called from AltLoader
- Which basically just does the second part of mcleaks api the joinserver HTTPS POST request
- This requires a lot more parameters this time and this is how AltLoader gets those parameter
```java
private void handle(final NetworkManager networkManager, final S01PacketEncryptionRequest packetIn) {
	final SecretKey secretkey = CryptManager.createNewSharedKey();
	String s = packetIn.getServerId();
	final PublicKey publickey = packetIn.getPublicKey();
	String serverIdHash = new BigInteger(CryptManager.getServerIdHash(s, publickey, secretkey)).toString(16);
	InetSocketAddress remoteAddress = (InetSocketAddress)networkManager.getRemoteAddress();
```
(CryptManager is a Minecraft class, ServerId is a response from the server, PublicKey too, serveridhash is generated by the CryptManager out of those prev params and of course the remoteAddress which is the host address of the server)
- The next part inside the handle method just sends the POST request to the mcleaks server and waits for it to return true like described in the API of McLeaks, then in the callback handler of the HTTP Request
when the response is true from the mcleaks api it sends a C01PacketEncryptionResponse packet to the mc server you want to connect to.
```java
ModApi.joinServer(mcl.getMcLeaksSession(), mc.getSession().getUsername(), serverIdHash,
 remoteAddress.getHostName() + ":" + remoteAddress.getPort(), new net.mcleaks.mod.util.Callback() {
  public void done(Object o) {
   if (o == null) {
    return;
   }

   if ((o instanceof String)) {
    networkManager.channel().close();
    mc.displayGuiScreen(new net.mcleaks.mod.gui.GuiMCLeaksError((String) o));
    return;
   }

   networkManager.sendPacket(
    new C01PacketEncryptionResponse(secretkey, publickey, packetIn.getVerifyToken()),
    new GenericFutureListener() {
     public void operationComplete(Future p_operationComplete_1_)
     throws Exception {
      networkManager.enableEncryption(secretkey);
     }
    }, new GenericFutureListener[0]);
  }
 });
```
And this is basically all the magic:
- Redeem your token, save the username and session
- Handle the S01PacketEncryptionRequest  packet of ur client by
generating a secretkey and a serverIdHash with data of the packet
- Call the /joinserver of route of mcleaks, if they return true, it meants that they successfully
told the mojang api that the alt accounts wants to connect to that server
(they themself called https://sessionserver.mojang.com/session/minecraft/join which is something normally the client does, but they will do it for you, since they won't give out their accessToken)
- At this point everything is set up and you only need to respond to the mcServer with the C01PacketEncryptionResponse packet

One more thing I forgot to add, the code part where the altloader mod adds himself in the packet handler pipeline. As described earlier the mod listening for the GuiConnecting to open up on the screen.
```java
  @SubscribeEvent
  public void onGuiOpen(GuiOpenEvent event) {
    if ((mcl.getMcName() != null) && (((event.gui instanceof net.minecraft.client.gui.GuiMultiplayer)) || ((event.gui instanceof net.minecraft.client.gui.GuiDisconnected)) || ((event.gui instanceof GuiMCLeaksError)))) {
      net.mcleaks.mod.SessionManager.setSession(mcl.getMcName());
    }
    
    if ((!(event.gui instanceof GuiConnecting)) || (mcl.getMcLeaksSession() == null)) {
      return;
    }
    
    final GuiConnecting gui = (GuiConnecting)event.gui;
    
    new Thread(new Runnable()
    {
      public void run() {
        for (;;) {
          NetworkManager networkManager = (NetworkManager)net.mcleaks.mod.util.ReflectionUtil.getFieldByClass(gui, NetworkManager.class);
          
          if (networkManager != null) {
            networkManager.channel().pipeline().addBefore("packet_handler", "mcleaks_handler", new net.mcleaks.mod.network.MCLeaksPacketHandler());
            mcl.setCurrentNetworkManager(networkManager);
            break;
          }
          try
          {
            Thread.sleep(2L);
          } catch (InterruptedException e) {
            e.printStackTrace();
          }
        }
      }
    }).start();
  }
}
```
This isn't rlly neccessary since you want to implement it in mineflayer and things get probably handled different there(didnt yet look into the code).
All we need to do there is basically create another way of authenticating by outsourcing the https://sessionserver.mojang.com/session/minecraft/join request to mcleaks and never actually store our own accessToken. There probably is a way to still get the accessToken from mojang even if mcleaks doesnt allow it directly, but I would need to deep dive into the mojang api first.

**Comment by rom1504** [comment]
I don't know if we want to support mcleaks considering mojang won't like it too much (+ it's kind of borderline ethic wise). I'm fine with the existence of an external plugin for mcleaks though.

**Comment by The-Box1** [comment]
Sorry to rejuvenate this old issue but I'm curious to see if any progress has been made in finding if it is possible to get the accessToken from McLeaks. @skullteria I know you've probably onto a new project by now, but did you ever figure out a way to do this?

**Comment by skullteria** [comment]
If you google for `recaptcha solver` you find websites who over human captcha solver and a api.
They also have very low prices. All you gotta do is wire up their api with website of mcleaks, then you will able to get their accessToken without doing anything urself.

**Comment by The-Box1** [comment]
Thank you for the information.

Reading over this a second time I realized that I had misread some information which threw me off.

**Comment by The-Box1** [comment]
Thank you. Also, @skullteria, do you know where to listen for the S01PacketEncryptionRequest? Does MCLeaks have their own auth server similar to minecraft that is used to login?
