### ISSUE TITLE
Possible Feature: Get TPS

### ISSUE THREAD

**Issue by rex9135** [PrismarineJS/mineflayer#822]
Not an issue but would it be possible that in future versions you are able to get the TPS of the server that the bot is on.

**Comment by rom1504** [comment]
That would always return 20.
Is that what you want ?

**Comment by wvffle** [comment]
Please stick to the issue template.

**Comment by rex9135** [comment]
> Please stick to the issue template.
Sorry, didn't realize there was an issue template

**Comment by rom1504** [comment]
Ok so `const getTps = () => 20` that's your function.
Solved

**Comment by plexigras** [comment]
you could use the time of day difference

**Comment by rom1504** [comment]
To do what ? The server cannot change the tps.

**Comment by EvilSourcerer** [comment]
The server might have a TPS lower than 20 though, because of lag

**Comment by rom1504** [comment]
No it just skip ticks

**Comment by rex9135** [comment]
the server’s TPS (ticks per second) changes based on lag, low TPS slows the server down, it is not always 20, as you said.

**Comment by rom1504** [comment]
Does it really change ? How can you see that ?
The vanilla servers usually says "skipping n ticks" when lagging.
That means its tps is still 20, just that some ticks are not computed.

**Comment by roblabla** [comment]
It's not possible to get the server's TPS. It's invisible to the client (unless you use heuristics like the amount of position updates per second - IIRC the server only sends one position update per tick). The server will skip missing ticks, so to the client, it will always look like it's running at 20TPS, regardless of server conditions.

**Comment by rom1504** [comment]
It's always 20 tps, even to the server, that's my point.

**Comment by rex9135** [comment]
Using certain mods, you are able to get an overlay that has a TPS Counter.
You are also able to view it on servers with specific plugins (such as
Essentials) where typing /TPS will show the TPS from the last 1,5,15
minutes.

**Comment by roblabla** [comment]
@rom1504 The actual number of tick executed is not 20. It allows measuring server performance, but is invisible to the client.

@rex9135 You can do that by using a combination of `bot.chat("/TPS")` and `bot._client.on('chat')`. Mineflayer can't add this, since it requires specific plugins on the server.

**Comment by rom1504** [comment]
If the server gets stuck it just skips ticks.
So yes it's definitely always at 20 ticks/s but some of these ticks have
not been processed.
What you are interested here in is processed tick / s which may vary.

**Comment by rom1504** [comment]
This issue is a duplicate of another open issue though

**Comment by wvffle** [comment]
The amount of **processed** ticks per second go down.

Server still runs on 20tps

**Comment by roblabla** [comment]
The TPS will still be 20 even if 5 are skipped. The server will just process multiple ticks in a single "tick". To give you an example, say the user moves at 1 block per tick. This means you move at 20 blocks per second. If you skip a tick, you'll still move at 20 blocks per second, it's just that the next tick will make you move 2 blocks instead of 1 to compensate for the missing tick. So what you want isn't the number of ticks per second, but how many ticks have actually been processed "at the right time". This is important because, to the client, the TPS is **always** 20. Even if the server calculated no ticks in a full second, the client will be completely blind to this.

For this reason, there's no way, on the protocol side of things, to get the processed TPS client-side. Some servers have a command to get the processed TPS, in which case just run the command and get the resulting chat message. If that's not available, then you're shit out of luck. You might be able to build a kludge that looks at different events to try to inferred if the server is actually processing all 20 TPS individually, but that's unlikely to be reliable, if it's even doable.

**Comment by SiebeDW** [comment]
```js
function getTps (bot, cb) {
  var i = 0
  var tps = 0
  run()
  function run () {
    var age = parseInt(bot.time.age)
    setTimeout(() => {
      var n = parseInt(bot.time.age) - age
      if (n === 20) {
        tps++
      }
      i++
      if (i < 20) {
        run()
      } else {
        cb(tps)
      }
    }, 1000)
  }
}
```
This is a working script that can get the server tps but it takes 20 seconds to get.

Example usage:
```js
bot.on('chat', function (username) {
  if (username === bot.username) return
  bot.chat('Getting tps this takes 20 seconds...')
  getTps(bot, tps => {
    bot.chat('Tps: ' + tps)
  })
})
```

**Comment by SiebeDW** [comment]
Ok so i made a new code that is much more accurate and it takes 0 seconds to get the tps with getTps(). Only thing is that it takes 20 seconds to start getting an accurate result because it first needs to fill a list.
```js
var calcTps = []
function run (bot) {
  var time = parseInt(bot.time.age)
  setTimeout(() => {
    var diff = parseInt(bot.time.age) - time

    calcTps.push(diff)
    if (calcTps.length > 20) {
      calcTps.shift()
    }
    run(bot)
  }, 1000)
}
function getTps () {
  return calcTps.filter(tps => tps === 20).length
}
```

Example full code:
```js
var mineflayer = require('mineflayer')
var bot = mineflayer.createBot({
  host: 'localhost',
  port: 25565,
  username: 'testbot',
  version: false
})
bot.on('error', err => console.log(err))

bot.on('login', () => {
  bot.chat('Starting to calculate tps!')
  run(bot)
})

bot.on('chat', (username) => {
  if (username === bot.username) return
  bot.chat('Current tps: ' + getTps())
})

var calcTps = []
function run (bot) {
  var time = parseInt(bot.time.age)
  setTimeout(() => {
    var diff = parseInt(bot.time.age) - time

    calcTps.push(diff)
    if (calcTps.length > 20) {
      calcTps.shift()
    }
    run(bot)
  }, 1000)
}
function getTps () {
  return calcTps.filter(tps => tps === 20).length
}
```

I think this is the best code for accurate results.

**Comment by SiebeDW** [comment]
My code above is now a [npm package](https://www.npmjs.com/package/mineflayer-tps).
You can find the source code [here](https://github.com/SiebeDW/mineflayer-tps).
