### ISSUE TITLE
no work: keepAlive, loop and and repeat the script loses the connection to the server

### ISSUE THREAD

**Issue by Escanor2019** [PrismarineJS/mineflayer#913]
look at the script
the first time that the connection is not lost, the bot does not remain active "keepAlive" and is only executing 1 of the 4 bots.
![image](https://user-images.githubusercontent.com/47899748/74669114-477b8900-5185-11ea-8b45-2b0157746128.png)
it is losing connection with the server if I run it twice in my real client minecraft.
sometimes runs 2 bots, but I’ve never seen 3

**Comment by Escanor2019** [comment]
i try async function
![image](https://user-images.githubusercontent.com/47899748/74670633-57e13300-5188-11ea-9b15-14d2825d726b.png)

**Comment by wvffle** [comment]
1. I've created issue templates with some purpose **Stick to them**
2. Do some research yourself in the first place: https://stackoverflow.com/a/17637900
3. Here is a fix for your async function: https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/sync-async/ch1.md#a-program-in-chunks
4. If you asked on discord and guys there said that you have to give the context then give this context to them. 
5.The solution to your problem is probably to defer every bot login. You'd know if you asked on discord.
6. I don't think that `keepAlive` has anything to do with that
7. Code in ` ```js ``` ` tags is much more readable than the screenshot
8. The title is not descriptive at all. I didn't understand what's your problem

**Comment by Escanor2019** [comment]
I wasted time seeing a ready solution.

If I had started this in C and using the minecraft protocols wiki I would have already finished.

you are dumber than 1 monkey

I don't know why you program, but you have in the future as any type of developer.

You don't create products and solutions, you create problems with a bunch of monkey followers.

**Comment by rom1504** [comment]
I blocked @Escanor2019 as he is rude and aggressive.
